package br.com.tcc.interfaceGrafica;

import br.com.tcc.bancoRelacional.Banco;
import br.com.tcc.conexao.relacional.Conexao;
import br.com.tcc.auxiliares.Mapeamento;
import br.com.tcc.auxiliares.ModeloTabela;
import br.com.tcc.auxiliares.No;
import br.com.tcc.bancoRelacional.Coluna;
import br.com.tcc.bancoRelacional.Tabela;
import br.com.tcc.conexao.nosql.documentos.ConexaoMongoDB;
import br.com.tcc.migracao.documentos.MongodbDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Claysllan
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAba1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JComboboxBanco = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLocal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPorta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBanco = new javax.swing.JTextField();
        jButtonProsseguirTela1 = new javax.swing.JButton();
        jPanelAba2 = new javax.swing.JPanel();
        jButtonProsseguirTela2 = new javax.swing.JButton();
        jLabelInformacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTabelasBanco = new javax.swing.JTable();
        jButtonSelecionarTodas = new javax.swing.JButton();
        jPanelAba3 = new javax.swing.JPanel();
        jComboBoxTipoBanco = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxBancoDestino = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIPBancoDestino = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPortaBancoDestino = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldUsuarioBancoDestino = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSenhaBancoDestino = new javax.swing.JTextField();
        jButtonProsseguirTela3 = new javax.swing.JButton();
        jPanelAba4 = new javax.swing.JPanel();
        jProgressBarMigracao = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInformacoes = new javax.swing.JTextArea();
        jToggleButtonConcluir = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btSobre = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RelationalToNoSQL");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        jTabbedPane1.setEnabled(false);

        jLabel1.setText("Selecione o Banco de dados de Origem*:");

        JComboboxBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PostgreSQL", "MySQL", "Oracle", "SQL Server", "Fireboard", "SQLite" }));
        JComboboxBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboboxBancoActionPerformed(evt);
            }
        });

        jLabel3.setText("Informe o IP do Banco de Origem*:");

        jTextFieldLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLocalActionPerformed(evt);
            }
        });

        jLabel4.setText("Informe a porta  do Banco de Origem:");

        jTextFieldPorta.setToolTipText("");
        jTextFieldPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPortaActionPerformed(evt);
            }
        });

        jLabel5.setText("Informe o nome de usuário do Banco de Origem*:");

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setText("Informe a senha do Banco de Origem*:");

        jLabel7.setText("Informe o database que será migrado*:");

        jTextFieldBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBancoActionPerformed(evt);
            }
        });

        jButtonProsseguirTela1.setText("Prosseguir");
        jButtonProsseguirTela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProsseguirTela1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAba1Layout = new javax.swing.GroupLayout(jPanelAba1);
        jPanelAba1.setLayout(jPanelAba1Layout);
        jPanelAba1Layout.setHorizontalGroup(
            jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAba1Layout.createSequentialGroup()
                .addContainerGap(397, Short.MAX_VALUE)
                .addComponent(jButtonProsseguirTela1)
                .addContainerGap())
            .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAba1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addGap(35, 35, 35)
                    .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JComboboxBanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldLocal)
                        .addComponent(jTextFieldPorta)
                        .addComponent(jTextFieldBanco)
                        .addComponent(jTextFieldUsuario)
                        .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelAba1Layout.setVerticalGroup(
            jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAba1Layout.createSequentialGroup()
                .addGap(0, 260, Short.MAX_VALUE)
                .addComponent(jButtonProsseguirTela1))
            .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAba1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(JComboboxBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Conexão", jPanelAba1);

        jButtonProsseguirTela2.setText("Prosseguir");
        jButtonProsseguirTela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProsseguirTela2ActionPerformed(evt);
            }
        });

        jLabelInformacoes.setText("Teste");

        jTableTabelasBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTabelasBanco);

        jButtonSelecionarTodas.setText("Selecionar Todas");
        jButtonSelecionarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAba2Layout = new javax.swing.GroupLayout(jPanelAba2);
        jPanelAba2.setLayout(jPanelAba2Layout);
        jPanelAba2Layout.setHorizontalGroup(
            jPanelAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAba2Layout.createSequentialGroup()
                        .addComponent(jLabelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelecionarTodas))
                    .addGroup(jPanelAba2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonProsseguirTela2)))
                .addContainerGap())
        );
        jPanelAba2Layout.setVerticalGroup(
            jPanelAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelecionarTodas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonProsseguirTela2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mapeamento", jPanelAba2);

        jComboBoxTipoBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chave-valor", "Orientado a documentos", "Orientado a colunas", "Orientado a grafos" }));
        jComboBoxTipoBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoBancoActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione o modelo do banco*:");

        jLabel8.setText("Selecione o banco*:");

        jComboBoxBancoDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Redis", "Riak", "GenieDB" }));

        jLabel10.setText("Informe o IP do banco de destino*:");

        jLabel11.setText("Informe a porta do banco de destino*:");

        jLabel12.setText("Informe o usuário (se houver): ");

        jLabel13.setText("Informe a senha (se houver): ");

        jButtonProsseguirTela3.setText("Prosseguir");
        jButtonProsseguirTela3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProsseguirTela3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAba3Layout = new javax.swing.GroupLayout(jPanelAba3);
        jPanelAba3.setLayout(jPanelAba3Layout);
        jPanelAba3Layout.setHorizontalGroup(
            jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAba3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAba3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(jComboBoxTipoBanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelAba3Layout.createSequentialGroup()
                        .addGroup(jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(21, 21, 21)
                        .addGroup(jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxBancoDestino, 0, 205, Short.MAX_VALUE)
                            .addComponent(jTextFieldIPBancoDestino)
                            .addComponent(jTextFieldPortaBancoDestino)
                            .addComponent(jTextFieldUsuarioBancoDestino)
                            .addComponent(jTextFieldSenhaBancoDestino)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAba3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonProsseguirTela3)))
                .addContainerGap())
        );
        jPanelAba3Layout.setVerticalGroup(
            jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAba3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxBancoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldIPBancoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPortaBancoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldUsuarioBancoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAba3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldSenhaBancoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButtonProsseguirTela3)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Destino", jPanelAba3);

        jProgressBarMigracao.setToolTipText("");
        jProgressBarMigracao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setText("Processo:");

        jTextAreaInformacoes.setEditable(false);
        jTextAreaInformacoes.setColumns(20);
        jTextAreaInformacoes.setRows(5);
        jScrollPane2.setViewportView(jTextAreaInformacoes);

        jToggleButtonConcluir.setText("Concluir");
        jToggleButtonConcluir.setEnabled(false);
        jToggleButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonConcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAba4Layout = new javax.swing.GroupLayout(jPanelAba4);
        jPanelAba4.setLayout(jPanelAba4Layout);
        jPanelAba4Layout.setHorizontalGroup(
            jPanelAba4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAba4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAba4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(jPanelAba4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jProgressBarMigracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAba4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButtonConcluir)))
                .addContainerGap())
        );
        jPanelAba4Layout.setVerticalGroup(
            jPanelAba4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAba4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarMigracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonConcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Migração", jPanelAba4);

        jMenu1.setText("Sobre");

        btSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/information.png"))); // NOI18N
        btSobre.setText("Sobre");
        btSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobreActionPerformed(evt);
            }
        });
        jMenu1.add(btSobre);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");

        btSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jMenu2.add(btSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSobreActionPerformed

    private void JComboboxBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboboxBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboboxBancoActionPerformed

    private void jTextFieldLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLocalActionPerformed

    private void jTextFieldPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPortaActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jTextFieldBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBancoActionPerformed

    private void jButtonProsseguirTela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProsseguirTela1ActionPerformed
        if (jTextFieldLocal.getText().trim().equals("") || jTextFieldPorta.getText().trim().equals("")
                || jTextFieldUsuario.getText().trim().equals("") || new String(jPasswordFieldSenha.getPassword()).trim().equals("")
                || jTextFieldBanco.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe todos os campos obrigratórios!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            String tipoBanco = JComboboxBanco.getSelectedItem().toString();
            String local = jTextFieldLocal.getText();
            String porta = jTextFieldPorta.getText();
            String nomeBanco = jTextFieldBanco.getText();
            String usuario = jTextFieldUsuario.getText();
            String senha = new String(jPasswordFieldSenha.getPassword());
            conexaoRelacional = new Conexao(tipoBanco, local, porta, nomeBanco, usuario, senha);
            if (conexaoRelacional.conectar()) {
                jTabbedPane1.setSelectedIndex(1);
                try {
                    Mapeamento m = new Mapeamento(conexaoRelacional);
                    jLabelInformacoes.setText(m.imprmirInformacoesMetadata());
                    bd = m.mapearBanco();
                    mostrarTabelas(bd);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NumberFormatException n) {
                    JOptionPane.showMessageDialog(null, "A porta informada está incorreta!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButtonProsseguirTela1ActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void jButtonProsseguirTela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProsseguirTela2ActionPerformed
        if (!validarTabelas()) {
            JOptionPane.showMessageDialog(null, "Há tabelas relacionadas não selecionadas!"
                    + "\nSe selecionar uma tabela que tenha relacionamento, favor selecionar a tabela referenciada também!", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<String> stringAuxiliar = modelo.getTabelasNaoSelecionadas();
            for (String s : stringAuxiliar) {
                bd.removeTabela(s);
            }
            jTabbedPane1.setSelectedIndex(2);
        }
    }//GEN-LAST:event_jButtonProsseguirTela2ActionPerformed

    private void jButtonSelecionarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarTodasActionPerformed
        modelo.selecionaTodas();
    }//GEN-LAST:event_jButtonSelecionarTodasActionPerformed

    private void jComboBoxTipoBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoBancoActionPerformed
        DefaultComboBoxModel cvModel = new DefaultComboBoxModel(new String[]{"Redis", "Riak", "GenieDB"});
        DefaultComboBoxModel docModel = new DefaultComboBoxModel(new String[]{"MongoDB", "CouchBD"});
        DefaultComboBoxModel colunModel = new DefaultComboBoxModel(new String[]{"Cassandra", "HBase", "Hypertable"});
        DefaultComboBoxModel grafModel = new DefaultComboBoxModel(new String[]{"Neo4j", "AllegroGraph", "Virtuoso"});
        if ("Chave-valor".equals(jComboBoxTipoBanco.getSelectedItem())) {
            jComboBoxBancoDestino.setModel(cvModel);
        } else if ("Orientado a documentos".equals(jComboBoxTipoBanco.getSelectedItem())) {
            jComboBoxBancoDestino.setModel(docModel);
        } else if ("Orientado a colunas".equals(jComboBoxTipoBanco.getSelectedItem())) {
            jComboBoxBancoDestino.setModel(colunModel);
        } else if ("Orientado a grafos".equals(jComboBoxTipoBanco.getSelectedItem())) {
            jComboBoxBancoDestino.setModel(grafModel);
        }
    }//GEN-LAST:event_jComboBoxTipoBancoActionPerformed

    private void jButtonProsseguirTela3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProsseguirTela3ActionPerformed
        if (verificarBancoDestino()) {
            jTabbedPane1.setSelectedIndex(3);
            JOptionPane.showMessageDialog(null, "Banco de dados Destino Conectado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "O processo de migração será iniciado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            jTextAreaInformacoes.setText("Migrando banco de dados...");
            if (bancoDestino.equals("MongoDB")) {
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        jProgressBarMigracao.setIndeterminate(true);
                    }
                });
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        MongodbDAO mongo = new MongodbDAO(mongoConexao.getMongoClient());
                        No arvore = criaArvore(bd);
                        long tempoInicio = System.currentTimeMillis();
                        try {
                            atualizaAreaInformacoes("Criando Banco de dados: " + jTextFieldBanco.getText());
                            atualizaAreaInformacoes("\nMigrando tabelas e dados...");
                            mongo.migrarDados(conexaoRelacional, bd, jTextFieldBanco.getText(), arvore);
                            atualizaAreaInformacoes("\nTabelas e dados migrados...");
                            atualizaAreaInformacoes("\nTratando os relacionamentos das tabelas...");
                            mongo.trataRelacionamentos(bd, arvore, jTextFieldBanco.getText());
                            atualizaAreaInformacoes("\nRelaciomanetos concluidos...");
                            atualizaAreaInformacoes("\nValidando tabelas migradas");
                            if (mongo.validar(conexaoRelacional, bd, jTextFieldBanco.getText())) {
                                atualizaAreaInformacoes("\nBanco de dados migrado com sucesso...");
                                jProgressBarMigracao.setStringPainted(true);
                                jProgressBarMigracao.setString("Migração Completa.");
                                jProgressBarMigracao.setIndeterminate(false);
                                jToggleButtonConcluir.setEnabled(true);
                            } else {
                                JOptionPane.showMessageDialog(null, "Erro na migração. Refaça a operação.", "ERRO", JOptionPane.ERROR_MESSAGE);
                            }
                            atualizaAreaInformacoes("\nTempo Total: " + TimeUnit.MILLISECONDS.toMinutes(System.currentTimeMillis() - tempoInicio) + " minutos");
                        } catch (SQLException ex) {
                            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
            }
        }
    }//GEN-LAST:event_jButtonProsseguirTela3ActionPerformed

    private void jToggleButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonConcluirActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jToggleButtonConcluirActionPerformed

    public void mostrarTabelas(Banco bd) {
        modelo.addRow(bd);
        jTableTabelasBanco.setModel(modelo);
    }

    public Boolean validarTabelas() {
        ArrayList<String> tabelasSelecionadas = modelo.getTabelasSelecionadas();
        ArrayList<String> tabelasNSelecionadas = modelo.getTabelasNaoSelecionadas();
        ArrayList<Coluna> colunas = new ArrayList();
        int cont = 0;
        for (String tabelasSelecionada : tabelasSelecionadas) {
            for (Tabela t : bd.getTabelas()) {
                if (t.getNome().equalsIgnoreCase(tabelasSelecionada)) {
                    colunas = t.getColunas();
                    for (Coluna c : colunas) {
                        if (tabelasNSelecionadas.contains(c.getTabelaForeignKeyReferencia())) {
                            return false;
                        }
                    }
                }
            }
        }
        return true;
    }

    public boolean verificarBancoDestino() {
        try {
            if (jComboBoxBancoDestino.getSelectedItem().equals("MongoDB")) {
                bancoDestino = "MongoDB";
                mongoConexao = new ConexaoMongoDB();
                return mongoConexao.conectar(jTextFieldIPBancoDestino.getText(), Integer.parseInt(jTextFieldPortaBancoDestino.getText()));
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um banco de dados!", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(null, "A porta informada está incorreta!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    public No criaArvore(Banco bd) {
        No raiz = new No(null);
        raiz.setNomeTabela("root");
        boolean achou = false;
        for (Tabela t : bd.getTabelas()) {
            for (Coluna c : t.getColunas()) {
                if (c.isChaveEstrangeira()) {
                    No jaAdicionou = raiz.buscaPai(t.getNome(), raiz);
                    if (jaAdicionou != null) {
                        No aux = raiz.buscaPai(c.getTabelaForeignKeyReferencia(), raiz);
                        if (aux == null) {
                            raiz.addFilho(jaAdicionou, c.getTabelaForeignKeyReferencia());
                            achou = true;
                        } else {
                            jaAdicionou.getFilho().add(aux);
                            if (aux.getPai().getNomeTabela().equalsIgnoreCase("root")) {
                                aux.getPai().getFilho().remove(aux);
                            }
                            achou = true;
                        }
                    } else {
                        No aux = raiz.buscaPai(c.getTabelaForeignKeyReferencia(), raiz);
                        if (aux == null) {
                            No filho = raiz.addFilho(raiz, t.getNome());
                            raiz.addFilho(filho, c.getTabelaForeignKeyReferencia());
                            achou = true;
                        } else {
                            if (aux.getPai().getNomeTabela().equalsIgnoreCase("root")) {
                                No pai = aux.getPai().addFilho(aux.getPai(), t.getNome());
                                pai.getFilho().add(aux);
                                aux.getPai().getFilho().remove(aux);
                            } else {
                                No pai = aux.getPai().addFilho(aux.getPai().getPai(), t.getNome());
                                pai.getFilho().add(aux);
                            }
                            achou = true;
                        }
                    }
                }
            }
            if (!achou) {
                No aux = raiz.buscaPai(t.getNome(), raiz);
                if (aux == null) {
                    raiz.addFilho(raiz, t.getNome());
                }
            }
            achou = false;
        }
        return raiz;
    }

    public void atualizaAreaInformacoes(String str) {
        jTextAreaInformacoes.append(str);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaInicial().setVisible(true);
        });
    }
    ModeloTabela modelo = new ModeloTabela();
    Banco bd;
    ConexaoMongoDB mongoConexao;
    Conexao conexaoRelacional;
    String bancoDestino;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboboxBanco;
    private javax.swing.JMenuItem btSair;
    private javax.swing.JMenuItem btSobre;
    private javax.swing.JButton jButtonProsseguirTela1;
    private javax.swing.JButton jButtonProsseguirTela2;
    private javax.swing.JButton jButtonProsseguirTela3;
    private javax.swing.JButton jButtonSelecionarTodas;
    private javax.swing.JComboBox<String> jComboBoxBancoDestino;
    private javax.swing.JComboBox<String> jComboBoxTipoBanco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelInformacoes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelAba1;
    private javax.swing.JPanel jPanelAba2;
    private javax.swing.JPanel jPanelAba3;
    private javax.swing.JPanel jPanelAba4;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JProgressBar jProgressBarMigracao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableTabelasBanco;
    private javax.swing.JTextArea jTextAreaInformacoes;
    private javax.swing.JTextField jTextFieldBanco;
    private javax.swing.JTextField jTextFieldIPBancoDestino;
    private javax.swing.JTextField jTextFieldLocal;
    private javax.swing.JTextField jTextFieldPorta;
    private javax.swing.JTextField jTextFieldPortaBancoDestino;
    private javax.swing.JTextField jTextFieldSenhaBancoDestino;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JTextField jTextFieldUsuarioBancoDestino;
    private javax.swing.JToggleButton jToggleButtonConcluir;
    // End of variables declaration//GEN-END:variables
}
